package com.amhsrobotics.circuitsim.hardware;

public enum HardwareType {

    WIRE, DOUBLESANDCRAB, TRIPLESANDCRAB, PDP, VRM, ROBORIO, TALON, PCM, SPARK, MOTOR775, FALCON, NEO, BREAKER, BATTERY, RADIO, ETHERNET, TUBING, EPLATE
}
